### ISSUE TITLE
Maybe convert project to a monorepository?

### ISSUE THREAD

**Issue by langri-sha** [mappum/webcoin#19]
I am not certain what complexity is entailed with managing a [monorepository](https://github.com/babel/babel/tree/master/packages) ([design document :memo:](https://github.com/babel/babel/blob/master/doc/design/monorepo.md)), but it appears that Webcoin could benefit if we collocate all the different projects together.

Some immediate obvious benefits:
- one GitHub repository (this is really powerful, take a moment to consider all the implications)
- managing inter-package dependencies and versions can be automated
- easier setup for over-arching work, like building documentation by reaching into every project #3 

Some qualities that are retained:
- each project lives as an independent package in the registry
- different projects can still continue to develop on their own; Babel's packages are synced on the major version, but otherwise have an independent release cycle, just to point out that a monorepo doesn't force you to always update all the packages when one changes in case someone is already familiar with React's release cycles

**Comment by mappum** [comment]
Thanks for the proposal, that's an interesting idea. I wasn't aware that's how babel organized their code, and it seems like it works well for them. However, I am satisfied with separate repos as it makes it easier for discovery, issues, and pull requests since they are normal repos, which is what people are used to. Also, many of the modules are completely independent and don't need to be used with Webcoin (for instance, [`bitcoin-protocol`](https://github.com/mappum/bitcoin-protocol)), so it wouldn't make sense to limit their usefulness.

**Comment by cellvia** [comment]
cool, makes sense RE: issues, discovery, etc.  just to be clear on one point, in a monorepo approach submodules still get published independently so `bitcoin-protocol` for ex would still exist on npm on its own if desired.   thanks @keppel for pointing me to this issue in answer to my other question!
